version: '3'

services:
  main:
    container_name: Node.js
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: Postgres
    image: postgres:15-alpine
    networks:
      - webnet
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:

volumes:
  pgdata:
